name: weather
description: A new Weather application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: FjallaOne
      fonts:
        - asset: fonts/FjallaOne-Regular.ttf

    - family: WorkSans
      fonts:
        - asset: fonts/WorkSans-Regular.ttf